version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
    command: -c fsync=off -c full_page_writes=off -c synchronous_commit=off -c max_connections=500